```mermaid
flowchart LR
  CUSTOMERS[OPT_LAB_CLONE_3.RETAIL.CUSTOMERS]
  ORDERS[OPT_LAB_CLONE_3.RETAIL.ORDERS]
  V[OPT_LAB_CLONE_3.RETAIL.V_CUSTOMER_ORDER_SUMMARY]

  CUSTOMERS --> V
  ORDERS --> V
```
