-- Object: HAFID_OPTIM_CLONE_1.PIPELINE_MART.VW_PRODUCT_PERFORMANCE
-- Type: VIEW
-- Warehouse: ADF_WH
-- Execution Mode: APPLY
-- Execution ID: exec-2026-06-30T00:00:08Z
-- Timestamp (UTC): 2026-06-30T00:00:08Z

CREATE OR REPLACE VIEW HAFID_OPTIM_CLONE_1.PIPELINE_MART.VW_PRODUCT_PERFORMANCE AS
WITH base AS (
    SELECT
        PRODUCT_ID,
        PRODUCT_CATEGORY,
        PRODUCT_SUBCATEGORY,
        NET_AMOUNT,
        ORDER_ID,
        QUANTITY,
        ORDER_DATE
    FROM HAFID_OPTIM_CLONE_1.PIPELINE_DWH.FACT_SALES
),
-- Reusable projection with derived metrics and price tier
product_agg AS (
    SELECT
        PRODUCT_ID,
        PRODUCT_CATEGORY,
        PRODUCT_SUBCATEGORY,
        ORDER_DATE,
        NET_AMOUNT,
        ORDER_ID,
        QUANTITY,
        -- Precompute unit price for PRICE_TIER classification
        CASE
            WHEN QUANTITY > 0 THEN NET_AMOUNT / NULLIF(QUANTITY, 0)
            ELSE NULL
        END AS UNIT_PRICE
    FROM base
)
SELECT
    'CURRENT_QUARTER' AS PERIOD_TYPE,
    PRODUCT_ID,
    PRODUCT_CATEGORY,
    PRODUCT_SUBCATEGORY,
    SUM(NET_AMOUNT) AS REVENUE,
    COUNT(DISTINCT ORDER_ID) AS UNIQUE_ORDERS,
    SUM(QUANTITY) AS UNITS_SOLD,
    CASE
        WHEN SUM(QUANTITY) > 0 THEN
            CASE
                WHEN SUM(UNIT_PRICE * QUANTITY) / NULLIF(SUM(QUANTITY), 0) > 100 THEN 'HIGH'
                WHEN SUM(UNIT_PRICE * QUANTITY) / NULLIF(SUM(QUANTITY), 0) > 50  THEN 'MEDIUM'
                ELSE 'LOW'
            END
        ELSE 'NONE'
    END AS PRICE_TIER
FROM product_agg
WHERE ORDER_DATE >= DATEADD('month', -3, CURRENT_DATE())
  AND ORDER_DATE <  CURRENT_DATE()
GROUP BY
    PRODUCT_ID,
    PRODUCT_CATEGORY,
    PRODUCT_SUBCATEGORY

UNION ALL

SELECT
    'PREVIOUS_QUARTER' AS PERIOD_TYPE,
    PRODUCT_ID,
    PRODUCT_CATEGORY,
    PRODUCT_SUBCATEGORY,
    SUM(NET_AMOUNT) AS REVENUE,
    COUNT(DISTINCT ORDER_ID) AS UNIQUE_ORDERS,
    SUM(QUANTITY) AS UNITS_SOLD,
    CASE
        WHEN SUM(QUANTITY) > 0 THEN
            CASE
                WHEN SUM(UNIT_PRICE * QUANTITY) / NULLIF(SUM(QUANTITY), 0) > 100 THEN 'HIGH'
                WHEN SUM(UNIT_PRICE * QUANTITY) / NULLIF(SUM(QUANTITY), 0) > 50  THEN 'MEDIUM'
                ELSE 'LOW'
            END
        ELSE 'NONE'
    END AS PRICE_TIER
FROM product_agg
WHERE ORDER_DATE >= DATEADD('month', -6, CURRENT_DATE())
  AND ORDER_DATE <  DATEADD('month', -3, CURRENT_DATE())
GROUP BY
    PRODUCT_ID,
    PRODUCT_CATEGORY,
    PRODUCT_SUBCATEGORY

UNION ALL

SELECT
    'YEAR_AGO_QUARTER' AS PERIOD_TYPE,
    PRODUCT_ID,
    PRODUCT_CATEGORY,
    PRODUCT_SUBCATEGORY,
    SUM(NET_AMOUNT) AS REVENUE,
    COUNT(DISTINCT ORDER_ID) AS UNIQUE_ORDERS,
    SUM(QUANTITY) AS UNITS_SOLD,
    CASE
        WHEN SUM(QUANTITY) > 0 THEN
            CASE
                WHEN SUM(UNIT_PRICE * QUANTITY) / NULLIF(SUM(QUANTITY), 0) > 100 THEN 'HIGH'
                WHEN SUM(UNIT_PRICE * QUANTITY) / NULLIF(SUM(QUANTITY), 0) > 50  THEN 'MEDIUM'
                ELSE 'LOW'
            END
        ELSE 'NONE'
    END AS PRICE_TIER
FROM product_agg
WHERE ORDER_DATE >= DATEADD('month', -15, CURRENT_DATE())
  AND ORDER_DATE <  DATEADD('month', -12, CURRENT_DATE())
GROUP BY
    PRODUCT_ID,
    PRODUCT_CATEGORY,
    PRODUCT_SUBCATEGORY;
