-- Previous definition captured from execution payload
create or replace view VW_INVENTORY_HEALTH(
	PRODUCT_ID,
	WAREHOUSE_ID,
	QTY_ON_HAND,
	REORDER_POINT,
	LAST_RESTOCK,
	UNIT_COST,
	INVENTORY_VALUE,
	DAILY_VELOCITY,
	DAYS_OF_SUPPLY,
	STOCK_STATUS
) as
WITH all_inventory AS (
    SELECT 
        ri.PAYLOAD:"product_id"::STRING AS PRODUCT_ID,
        ri.PAYLOAD:"warehouse_id"::STRING AS WAREHOUSE_ID,
        ri.PAYLOAD:"quantity_on_hand"::NUMBER AS QTY_ON_HAND,
        ri.PAYLOAD:"reorder_point"::NUMBER AS REORDER_POINT,
        ri.PAYLOAD:"last_restock_date"::STRING AS LAST_RESTOCK_DATE,
        ri.PAYLOAD:"unit_cost"::FLOAT AS UNIT_COST,
        ri._LOADED_AT,
        ROW_NUMBER() OVER (ORDER BY ri._LOADED_AT DESC) AS RN_GLOBAL,
        ROW_NUMBER() OVER (PARTITION BY ri.PAYLOAD:"product_id"::STRING, ri.PAYLOAD:"warehouse_id"::STRING ORDER BY ri._LOADED_AT DESC) AS RN_LATEST
    FROM HAFID_OPTIM_CLONE_1.PIPELINE_RAW.RAW_INVENTORY ri
),
sales_velocity AS (
    SELECT 
        PRODUCT_ID,
        SUM(QUANTITY) AS TOTAL_SOLD_90D,
        SUM(QUANTITY) / 90.0 AS DAILY_VELOCITY
    FROM HAFID_OPTIM_CLONE_1.PIPELINE_DWH.FACT_SALES
    WHERE ORDER_DATE >= DATEADD('day', -90, CURRENT_DATE())
    GROUP BY PRODUCT_ID
)
SELECT 
    ai.PRODUCT_ID, ai.WAREHOUSE_ID, ai.QTY_ON_HAND, ai.REORDER_POINT,
    TRY_TO_DATE(ai.LAST_RESTOCK_DATE) AS LAST_RESTOCK,
    ai.UNIT_COST,
    ai.QTY_ON_HAND * ai.UNIT_COST AS INVENTORY_VALUE,
    sv.DAILY_VELOCITY,
    CASE WHEN sv.DAILY_VELOCITY > 0 THEN ROUND(ai.QTY_ON_HAND / sv.DAILY_VELOCITY, 1) ELSE 999 END AS DAYS_OF_SUPPLY,
    CASE 
        WHEN ai.QTY_ON_HAND <= ai.REORDER_POINT THEN 'REORDER_NEEDED'
        WHEN ai.QTY_ON_HAND <= ai.REORDER_POINT * 1.5 THEN 'LOW_STOCK'
        WHEN sv.DAILY_VELOCITY > 0 AND ai.QTY_ON_HAND / sv.DAILY_VELOCITY > 180 THEN 'OVERSTOCK'
        ELSE 'HEALTHY'
    END AS STOCK_STATUS
FROM all_inventory ai
LEFT JOIN sales_velocity sv ON sv.PRODUCT_ID = ai.PRODUCT_ID
WHERE ai.RN_LATEST = 1;
