-- Object: OPT_LAB_CLONE_2.RETAIL.V_NEVER_ORDERED_PRODUCTS
-- Type: VIEW
-- Execution: exec-2026-06-30T00:01:37Z

CREATE OR REPLACE VIEW OPT_LAB_CLONE_2.RETAIL.V_NEVER_ORDERED_PRODUCTS AS
SELECT p.
FROM products p
WHERE p.product_id NOT IN (SELECT oi.product_id FROM order_items oi);
