create or replace view VW_EVENT_FUNNEL(
	EVENT_DATE,
	USER_ID,
	PAGE_VIEWS,
	ADD_TO_CARTS,
	CHECKOUTS,
	PURCHASES,
	CONVERSION_RATE
) as
SELECT 
    TO_DATE(e1.PAYLOAD:"timestamp"::STRING) AS EVENT_DATE,
    e1.PAYLOAD:"user_id"::STRING AS USER_ID,
    COUNT(DISTINCT CASE WHEN LOWER(e1.PAYLOAD:"event_type"::STRING) LIKE '%view%' THEN e1.PAYLOAD:"session_id"::STRING END) AS PAGE_VIEWS,
    COUNT(DISTINCT CASE WHEN LOWER(e1.PAYLOAD:"event_type"::STRING) LIKE '%cart%' THEN e1.PAYLOAD:"session_id"::STRING END) AS ADD_TO_CARTS,
    COUNT(DISTINCT CASE WHEN LOWER(e1.PAYLOAD:"event_type"::STRING) LIKE '%check%' THEN e1.PAYLOAD:"session_id"::STRING END) AS CHECKOUTS,
    COUNT(DISTINCT CASE WHEN LOWER(e1.PAYLOAD:"event_type"::STRING) LIKE '%purchase%' THEN e1.PAYLOAD:"session_id"::STRING END) AS PURCHASES,
    CASE 
        WHEN COUNT(DISTINCT CASE WHEN LOWER(e1.PAYLOAD:"event_type"::STRING) LIKE '%view%' THEN e1.PAYLOAD:"session_id"::STRING END) > 0
        THEN ROUND(
            COUNT(DISTINCT CASE WHEN LOWER(e1.PAYLOAD:"event_type"::STRING) LIKE '%purchase%' THEN e1.PAYLOAD:"session_id"::STRING END) * 100.0 /
            COUNT(DISTINCT CASE WHEN LOWER(e1.PAYLOAD:"event_type"::STRING) LIKE '%view%' THEN e1.PAYLOAD:"session_id"::STRING END)
        , 2)
        ELSE 0
    END AS CONVERSION_RATE
FROM HAFID_OPTIM_CLONE_1.PIPELINE_RAW.RAW_EVENTS e1
WHERE e1._LOADED_AT >= DATEADD('day', -90, CURRENT_TIMESTAMP())
GROUP BY 1, 2;