CREATE OR REPLACE VIEW HAFID_OPTIM_CLONE_1.PIPELINE_MART.VW_EVENT_FUNNEL AS
WITH base_events AS (
    SELECT
        -- Normalize event timestamp once
        TO_TIMESTAMP(e1.PAYLOAD:"timestamp"::STRING) AS EVENT_TS,
        TO_DATE(TO_TIMESTAMP(e1.PAYLOAD:"timestamp"::STRING)) AS EVENT_DATE,
        -- Extract core fields once
        e1.PAYLOAD:"user_id"::STRING  AS USER_ID,
        LOWER(e1.PAYLOAD:"event_type"::STRING) AS EVENT_TYPE_LOWER
    FROM HAFID_OPTIM_CLONE_1.PIPELINE_RAW.RAW_EVENTS e1
    WHERE e1._LOADED_AT >= DATEADD('day', -90, CURRENT_TIMESTAMP())
)
SELECT
    EVENT_DATE,
    USER_ID,
    -- Funnel step flags
    CASE WHEN POSITION('view'     IN EVENT_TYPE_LOWER)     > 0 THEN 1 ELSE 0 END AS IS_VIEW,
    CASE WHEN POSITION('cart'     IN EVENT_TYPE_LOWER)     > 0 THEN 1 ELSE 0 END AS IS_CART,
    CASE WHEN POSITION('check'    IN EVENT_TYPE_LOWER)     > 0 THEN 1 ELSE 0 END AS IS_CHECKOUT,
    CASE WHEN POSITION('purchase' IN EVENT_TYPE_LOWER)     > 0 THEN 1 ELSE 0 END AS IS_PURCHASE,

    -- Aggregate funnel metrics per day & user
    COUNT(*)                                                AS TOTAL_EVENTS,
    SUM(CASE WHEN POSITION('view'     IN EVENT_TYPE_LOWER) > 0 THEN 1 ELSE 0 END) AS VIEW_EVENTS,
    SUM(CASE WHEN POSITION('cart'     IN EVENT_TYPE_LOWER) > 0 THEN 1 ELSE 0 END) AS CART_EVENTS,
    SUM(CASE WHEN POSITION('check'    IN EVENT_TYPE_LOWER) > 0 THEN 1 ELSE 0 END) AS CHECKOUT_EVENTS,
    SUM(CASE WHEN POSITION('purchase' IN EVENT_TYPE_LOWER) > 0 THEN 1 ELSE 0 END) AS PURCHASE_EVENTS,

    -- Conversion rate from views to purchases
    CASE
        WHEN SUM(CASE WHEN POSITION('view' IN EVENT_TYPE_LOWER) > 0 THEN 1 ELSE 0 END) = 0
        THEN 0
        ELSE
            SUM(CASE WHEN POSITION('purchase' IN EVENT_TYPE_LOWER) > 0 THEN 1 ELSE 0 END)
            / SUM(CASE WHEN POSITION('view'     IN EVENT_TYPE_LOWER) > 0 THEN 1 ELSE 0 END)::FLOAT
    END AS CONVERSION_RATE
FROM base_events
GROUP BY
    EVENT_DATE,
    USER_ID;