```mermaid
erDiagram
  OPT_LAB_CLONE_3_RETAIL_ORDERS {
    NUMBER ORDER_ID
    TIMESTAMP_NTZ ORDER_DATE
    VARCHAR STATUS
    NUMBER CUSTOMER_ID
  }

  OPT_LAB_CLONE_3_RETAIL_CUSTOMERS {
    NUMBER CUSTOMER_ID
    VARCHAR FIRST_NAME
    VARCHAR LAST_NAME
    VARCHAR EMAIL
    VARCHAR PHONE  %% referenced by optimized view; validation failed because it does not exist
    VARCHAR STATUS
  }

  OPT_LAB_CLONE_3_RETAIL_ORDER_ITEMS {
    NUMBER ORDER_ID
    NUMBER ORDER_ITEM_ID
    NUMBER PRODUCT_ID
    NUMBER QUANTITY
    NUMBER UNIT_PRICE
  }

  OPT_LAB_CLONE_3_RETAIL_PRODUCTS {
    NUMBER PRODUCT_ID
    VARCHAR PRODUCT_NAME
    VARCHAR CATEGORY
  }

  OPT_LAB_CLONE_3_RETAIL_PAYMENTS {
    NUMBER ORDER_ID
    NUMBER AMOUNT
    VARCHAR METHOD
    VARCHAR STATUS
  }

  OPT_LAB_CLONE_3_RETAIL_ORDERS ||--o{ OPT_LAB_CLONE_3_RETAIL_ORDER_ITEMS : contains
  OPT_LAB_CLONE_3_RETAIL_PRODUCTS ||--o{ OPT_LAB_CLONE_3_RETAIL_ORDER_ITEMS : referenced_by
  OPT_LAB_CLONE_3_RETAIL_CUSTOMERS ||--o{ OPT_LAB_CLONE_3_RETAIL_ORDERS : places
  OPT_LAB_CLONE_3_RETAIL_ORDERS ||--o{ OPT_LAB_CLONE_3_RETAIL_PAYMENTS : has
```
