```mermaid
flowchart LR
  OPT_LAB_CLONE_5.RETAIL.CUSTOMERS["OPT_LAB_CLONE_5.RETAIL.CUSTOMERS"] --> OPT_LAB_CLONE_5.RETAIL.V_CUSTOMER_ORDER_SUMMARY["OPT_LAB_CLONE_5.RETAIL.V_CUSTOMER_ORDER_SUMMARY"]
  OPT_LAB_CLONE_5.RETAIL.ORDERS["OPT_LAB_CLONE_5.RETAIL.ORDERS"] --> OPT_LAB_CLONE_5.RETAIL.V_CUSTOMER_ORDER_SUMMARY["OPT_LAB_CLONE_5.RETAIL.V_CUSTOMER_ORDER_SUMMARY"]
```